let hours=document.getElementById("hours")
let minute=document.getElementById("minute")
let secound=document.getElementById("secound")
let day=document.getElementById("day")
let month=document.getElementById("month")
let years=document.getElementById("years")
let myDate=new Date()

hours.innerText=myDate.getHours()
minute.innerText=myDate.getMinutes()
secound.innerText=myDate.getSeconds()
day.innerText=myDate.getDay()
month.innerText=myDate.getMonth()
years.innerText=myDate.getFullYear()